/**
 * @author: dwi.setiyadi@gmail.com
*/

export const BINUSLOGGEDIN = 'BINUSLOGGEDIN';
export const BINUSLOGGEDOUT = 'BINUSLOGGEDOUT';

export const BINUSAUTHFETCH = 'BINUSAUTHFETCH';
export const BINUSAUTHSUCCESS = 'BINUSAUTHSUCCESS';
export const BINUSAUTHFAILED = 'BINUSAUTHFAILED';

export const CLASSFETCH = 'HOME.CLASSFETCH';
export const CLASSSUCCESS = 'HOME.CLASSSUCCESS';
export const CLASSFAILURE = 'HOME.CLASSFAILURE';

export const UPCOMINGCLASSFETCH = 'HOME.UPCOMINGCLASSFETCH';
export const UPCOMINGCLASSSUCCESS = 'HOME.UPCOMINGCLASSSUCCESS';
export const UPCOMINGCLASSFAILURE = 'HOME.UPCOMINGCLASSFAILURE';


export const APISIGNIN = 'api/login';
