export const USERLISTFETCH = 'USERLISTFETCH'
export const USERLISTSUCCESS = 'USERLLISTSUCCESS'
export const USERLISTFAILED = 'USERLISTFAILED'
export const USERLISTCLEAR = 'USERLISTCLEAR'
export const USERLISTTOTAL = 'USERLISTTOTAL'

export const APIUSER = 'api/users'
